assets/styles/components/BlockImprove.scss
assets/styles/components/_HeroSection.scss
assets/styles/shortcodes/PostsInfinitySlider.scss
lib/cleaner/assets.php
templates/content-archive-flow-templates.php

I fixed visual bugs and remove `elementor-frontend` styles from deregistring filter. For now we need them.
**Checklist**

Fixed some visual and functional bugs

---

assets/styles/common/_global.scss
assets/styles/components/BlockImprove.scss
assets/styles/components/_BlockImage.scss
assets/styles/components/_CookieBar.scss
assets/styles/components/compactHeader.scss
assets/styles/elements/_Button.scss
assets/styles/layouts/Footer.scss
assets/styles/shortcodes/PostsInfinitySlider.scss
base-scripts.php
lib/shortcodes/block-improve.php
templates/content-archive-features.php
templates/footer.php
templates/header.php
templates/newsletter-form.php

I changed styles, texts, js and added some new text, urls e.g.
**Checklist**

Fixing visual bugs and adding new content, texts e.g.

---

assets/styles/Elementor.scss
assets/styles/components/BlockImprove.scss
assets/styles/components/_BlockFullWidthBackground.scss
assets/styles/elements/_Button.scss
lib/shortcodes/block-improve.php

I created element `block-fullwidth-background` for home page. And some small styles changes in css
**Checklist**

Created element for home page

---

assets/styles/components/_BlockFullWidthBackground.scss

Fixed z-index and border radius in the element on home page
**Checklist**

Fixed z-index and border radius in the element on home page

---

base-scripts.php

: google tags
Close QualityUnit/web-issues#3078

[3078] fix: google tags

---

page.php
template-blog-header.php
templates/content-archive-videos.php
templates/content-single-glossary.php
templates/content-single-videos.php
templates/content-single.php

I removed generate shortcode from the templates 
**Checklist**
Close QualityUnit/web-issues#3385

[3385] Remove urlslab generator form code

---

assets/styles/common/_variables.scss
assets/styles/components/_Login.scss
assets/styles/elements/Header/_HeaderNavigationMain.scss
assets/styles/elements/_Button.scss
assets/styles/elements/_Logo.scss
assets/styles/layouts/Header.scss
templates/header.php

New design for header
**Checklist**
Close QualityUnit/web-issues#3085

[3085] Wider, new flowhunt header, footer

---

assets/styles/shortcodes/PostsInfinitySlider.scss
lib/functions/flows-thumbnail-svg-color-changer.php
lib/shortcodes/posts-infinity-slider.php

Changes proposed in this Pull Request
I rewrote code for infinity slider so that the rows don't go in one direction, but opposite each other.
**Checklist**
Close QualityUnit/web-issues#3063

[3063] FlowHunt homepage design - element infinity slider

---

assets/scripts/custom/data-scroll.js

remove markers from greensock anims
Close QualityUnit/web-issues#3062

[3062] fix: remove markers from greensock anims

---

assets/scripts/custom/data-scroll.js
assets/styles/components/_ScrollTrigger.scss

responsivity fixess to scroll trigger lock
Close QualityUnit/web-issues#3062

[3062] fix: responsivity

---

assets/styles/components/PostSidebar.scss
assets/styles/components/_ScrollTrigger.scss
assets/styles/layouts/Post.scss

post sidebar
Close QualityUnit/web-issues#3081

[3081] fix: post sidebar

---

assets/scripts/custom/filter.js
assets/styles/common/_global.scss
assets/styles/common/_gridLayout.scss
assets/styles/components/ElementorBlogPosts.scss
assets/styles/components/_ScrollTrigger.scss
lib/shortcodes.php
lib/shortcodes/elementor-blog-posts.php

Shortcode to show blog posts in homepage

Posts in homepage

---

assets/styles/common/_typography.scss
assets/styles/elements/_Button.scss

Changed font sizes on other pages like a elementor pages and small changes in the buttons
**Checklist**
Close QualityUnit/web-issues#3090

[3090] Wrong header size on FlowHunt

---

assets/scripts/custom/filter.js
lib/shortcodes/elementor-blog-posts.php

No url hash change for filtering blog items on homepage

fix: blog filtering on homepage without url hash change

---

assets/styles/common/_mixins.scss
assets/styles/common/_typography.scss
assets/styles/common/_variables.scss
assets/styles/components/_BlockImage.scss
assets/styles/components/_HeroSectionLanding.scss
assets/styles/components/_PricingPrograms.scss
assets/styles/elements/_Typography.scss
assets/styles/layouts/Footer.scss
assets/styles/pages/Pricing.scss
lib/custom-blocks/compact-header.php

Changes proposed in this Pull Request
I fixed visual bugs on the web. Added `urlslab-skip-lazy` to headers.
**Checklist**
Close QualityUnit/web-issues#3104
Close QualityUnit/web-issues#3096
Close QualityUnit/web-issues#3102
Close QualityUnit/web-issues#3102

Fixing visual bugs on the website

---

assets/scripts/custom/data-scroll.js
assets/styles/components/_HeroSectionLanding.scss
assets/styles/components/_ScrollTrigger.scss

Static scroller type on mobile (without images), new header for AI chatbot landing

feat: new header, scroll block on mobile static

---

assets/scripts/custom/data-scroll.js
assets/styles/components/_HeroSectionLanding.scss
assets/styles/components/_ScrollTrigger.scss

Fixing header with picture element, scroll trigger refresh on resize
Close QualityUnit/web-issues#3107

I3107 fixes scroll header

---

assets/styles/common/_mixins.scss

set width for wrappers
Close QualityUnit/web-issues#3112

[3112] fix: wrappers width

---

assets/styles/elements/_PostTypography.scss

Changes proposed in this Pull Request
I rewrote the styles for the lists because after updating gutenberg the list has a new class
**Checklist**
Close QualityUnit/web-issues#3088

[3088] Lists not working on all webs

---

assets/styles/components/_BlockImage.scss

I rewrote the styles for the scrollable section that was animated because the animations were removed.
**Checklist**
Close QualityUnit/web-issues#3113

[3113] Visual Improvement for AI Chatbot

---

assets/scripts/custom/compactHeader.js

compact header progress bar position jumping
Close QualityUnit/web-issues#3117

[3117] fix: compact header progress bar position

---

assets/scripts/custom/filter.js

features filtering
Close QualityUnit/web-issues#3108

[3108[ fix: features filtering

---

assets/styles/components/RelatedArticles.scss
assets/styles/elements/_Typography.scss
lib/custom-blocks/compact-header.php

slider fix for images in articles
Close QualityUnit/web-issues#3124

[3124] fix: slider for images in articles

---

.eslintrc
assets/scripts/custom/filter.js
assets/styles/components/Filter.scss
assets/styles/components/_Form.scss
assets/styles/components/compactHeader.scss
assets/styles/elements/_FilterMenu.scss
assets/styles/elements/_Inputs.scss
assets/styles/elements/_SearchField.scss
assets/styles/elements/_SortingMenu.scss
assets/styles/layouts/Header.scss
base-scripts.php
lib/assets.php
lib/custom-blocks/compact-header.php
lib/functions/component-imports.php

filtering not working on mobiles fixes
Close QualityUnit/web-issues#3125

[3125] fix: filtering not working on mobiles

---

assets/styles/components/compactHeader.scss

I added styles for align image to bottom of the header
**Checklist**
Close QualityUnit/web-issues#3129

[3129] Align image to bottom of the postype headers

---

assets/styles/common/_global.scss
assets/styles/common/elementor-custom.scss
assets/styles/components/_BlockFullWidthBackground.scss
assets/styles/components/_HeroSection.scss
assets/styles/components/_HeroSectionLanding.scss
assets/styles/components/compactHeader.scss
assets/styles/elements/_Button.scss
assets/styles/layouts/Footer.scss
assets/styles/layouts/Header.scss
assets/styles/shortcodes/PostsInfinitySlider.scss

I fixed styles for visual bug on the flowhunt. Primary on the mobile devices.
**Checklist**
Close QualityUnit/web-issues#3130

[3130] Fix some visual bugs on the mobile devices

---

templates/content-archive-flow-templates.php

I changed text what send Maria Stasova:
"FlowHunt lets you create all sorts of specialized chatbots and AI tools, all in one place—no more jumping between multiple websites. Browse the ever-expanding library of Flow templates to get a head start."
**Checklist**
Close QualityUnit/web-issues#3115

[3115] lorem impsum text flowhunt web page

---

templates/newsletter-form.php

I changed link for newsletter form
**Checklist**
Close QualityUnit/web-issues#3132

[3132] Change the newsletter subscription link in the footer form

---

lib/components/related-articles.php

Changed title in the related articles
**Checklist**
Close QualityUnit/web-issues#3128

[3128] Related Flows" section on feature pages

---

functions.php

I added a function that allows uploading a 4k image to the media
**Checklist**
Close QualityUnit/web-issues#3142

[3142] Fix blurry image on AI chatbot page

---

assets/styles/components/BlogTopPost.scss
assets/styles/layouts/_Blog.scss
assets/styles/pages/blog.scss
templates/content-archive.php

I rewrote grid layout for the blog archive page. 
**Checklist**
Close QualityUnit/web-issues#3138

[3138] Blog page layout is broken with 5 articles (FlowHunt)

---

assets/styles/components/compactHeader.scss
lib/custom-blocks/compact-header.php
templates/content-archive-features.php
templates/content-archive-flow-templates.php
templates/content-archive.php
templates/content-single-features.php
templates/content-single-flow-templates.php

I add next layout for the compact header what hasn't infinity img. it's a temporary solution until there is a design for blogs.
**Checklist**
Close QualityUnit/web-issues#3139

[3139] Longer headings overlap with thumbnails (FlowHunt)

---

assets/styles/layouts/_Posts.scss

I added styles for centering picture element what adding urlslab plugin
**Checklist**
Close QualityUnit/web-issues#3121

[3121] Aligned icons on the features archive

---

assets/styles/components/_BlockBoxes.scss

I added styles for title as a link
**Checklist**
Close QualityUnit/web-issues#3152

[3152] Fixed heading styles if the heading is a link

---

assets/styles/layouts/_Posts.scss
templates/content-archive-flow-templates.php

I fixed few visual bugs on archives.
**Checklist**

Fixed some visual bugs on archives

---

assets/styles/layouts/Post.scss
lib/components/post-sidebar.php

I rearranged the css files on individual pages because the content was jumping when loading
**Checklist**
Close QualityUnit/web-issues#3148

[3148] Rearranged css files for single post pages

---

lib/shortcodes/sidebar-banner.php

I added url to the button
**Checklist**
Close QualityUnit/web-issues#3160

[3160] CTA Button not working in Blog, Template Post types

---

base-scripts.php

I removed useless js script for demobar what we don't have on the flowhunt web.
**Checklist**
Close QualityUnit/la-marketing#3520

[3520] FH web / ReferenceError: trialButton is not defined

---

assets/styles/components/_BlockFullWidthBackground.scss

I fixed the link color if it is in the content
**Checklist**
Close QualityUnit/web-issues#3167

[3167] Anchor is almost invisible on dark background - FlowHunt Homepage

---

assets/styles/components/RelatedArticles.scss

I am center img if urlslab plugin add picture element over img element
**Checklist**
Close QualityUnit/web-issues#3151

[3151] Improvements for Related Flow

---

assets/styles/elements/_Checklist.scss
assets/styles/elements/_PostTypography.scss

I rewrote style for lists on the gutenberg pages
**Checklist**
Close QualityUnit/web-issues#3178

[3178] FlowHunt - Nested and ordered lists broken

---

templates/content-archive-tools.php

I replaced correct category for the filter on the archive page
**Checklist**
Close QualityUnit/web-issues#3172

[3172] Categories in AI Tools are incorrect

---

assets/styles/layouts/Post.scss

I fixed the width of the content if the page doesn't have a sidebar
**Checklist**
Close QualityUnit/web-issues#3202

[3202] FlowHunt - Content alignment on pages

---

assets/styles/components/Table.scss

I removed the css style that made the table wider than the content
**Checklist**
Close QualityUnit/web-issues#3164

[3164] Table too wide FlowHunt

---

assets/scripts/custom/filter.js
assets/styles/layouts/_Posts.scss
lib/custom-blocks/compact-header.php
templates/content-archive-features.php
templates/content-archive-flow-templates.php
templates/content-archive-glossary.php
templates/content-archive-tools.php
templates/content-archive-videos.php

I edited JS file for search in the custom post types. Added function for cancel submit search form after press enter key. Edited php code for post types. Tested in the all search forms in header
**Checklist**
Close QualityUnit/web-issues#3196

[3196] Search in template page redirect incorrectly

---

lib/functions.php
lib/functions/customize-gutenberg-button.php

I added function for customize gutenberg button. i added our classes `Button`  and add button text in to span. We need this html structure for styling this buttons.
**Checklist**
Close QualityUnit/web-issues#3166

[3166] CTA not working properly on FlowHunt from Elementor

---

base-scripts.php

I replaced old JS script for the chatbot
**Checklist**
Close QualityUnit/web-issues#3223

[3223] New chatbot with new integration code for whole website

---

lib/components/related-articles.php

I fixed warnings in the `related-articles.php`
**Checklist**
Close QualityUnit/web-issues#3245

[3245] Multiple PHP Warning related to Related Article

---

lib/functions.php
lib/functions/urlslab-related-posts.php
templates/content-single-features.php
templates/content-single-flow-templates.php
templates/content-single-glossary.php
templates/content-single-tools.php
templates/content-single.php

I replced our related articles with the urlslab related articles on the postypes and FAQ section from urlslab
**Checklist**
Close QualityUnit/web-issues#3256

[3256] FH web - add related resources to all pages of all post types

---

lib/shortcodes/sidebar-banner.php

sidebar try banner text changes
Close QualityUnit/web-issues#3255

[3255] fix: sidebar try banner text changes

---

assets/styles/components/_SimilarSources.scss

Edited styles for the related articles from urlslab
**Checklist**
Close QualityUnit/web-issues#3194

[3194] FlowHunt - related articles

---

templates/content-single-features.php
templates/content-single-flow-templates.php

missing image references
Close QualityUnit/web-issues#3292

[3292] fix: missing image references

---

.github/scripts/build-zip.sh
assets/styles/layouts/Post.scss

small  youtube video fix
Close QualityUnit/web-issues#3293

[3293] fix: youtube video

---

assets/scripts/custom/responsiveTable.js
assets/styles/pages/Pricing.scss

fix: table javascript

---

base-scripts.php

i changed max-width of the chatbot 
**Checklist**
Close QualityUnit/urlslab-issues#1330

[1330] The Chat Bubble of the new design of chatbot should be smaller

---

assets/scripts/custom/responsiveTable.js
assets/styles/common/_colorClasses.scss
assets/styles/common/_typography.scss
assets/styles/common/_variables.scss
assets/styles/components/ElementorBlogPosts.scss
assets/styles/components/ImageSwitcher.scss
assets/styles/components/SuccessStoriesGrid.scss
assets/styles/components/_BlockDark.scss
assets/styles/components/_HeroBanner.scss
assets/styles/components/_WavyLines.scss
assets/styles/elements/_Button.scss
assets/styles/elements/_Typography.scss
assets/styles/layouts/Footer.scss
assets/styles/shortcodes/Clients.scss

fix for max with header banner missing
Close QualityUnit/web-issues#3298
Close  https://github.com/QualityUnit/web-issues/issues/3084

[3298] fix: max width

---

assets/styles/common/_mixins.scss
assets/styles/pages/Pricing.scss

Change styles on pricing page flowhunt
- Go to pricing page and check margin between FAQ and above sections
**Checklist**
Close QualityUnit/web-issues#3295

[3295] fix margin on pricing page

---

assets/styles/components/_PricingPrograms.scss

Changed styles in label "Self-hosted" on pricing page
- Go to pricing page and check visual self-hosted label
in pricing Enterprise program section
**Checklist**
Close QualityUnit/web-issues#3301

[3301] - fix: added styles for self-hosted label on pricing page

---

assets/styles/common/_marginsPaddings.scss
assets/styles/common/_typography.scss
assets/styles/components/ImageSwitcher.scss
assets/styles/components/_BlockDark.scss

some components additional styling
Close QualityUnit/web-issues#3312

[3312] fix: some components additional styling

---

assets/scripts/app/custom_lightbox_youtube.js
assets/scripts/custom/blogLazyLoad.js
assets/styles/common/_lightbox.scss
assets/styles/components/_BlockDark.scss
assets/styles/layouts/_Blog.scss
lib/shortcodes/elementor-blog-posts.php

blog posts lazy loading fix, video controls on modal videos, blog posts bottom home page order
Close QualityUnit/web-issues#3320
Close QualityUnit/web-issues#3321
Close QualityUnit/web-issues#3329

[3329] fix: blog posts lazy loading

---

assets/scripts/custom/responsiveTable.js
assets/styles/common/_marginsPaddings.scss
assets/styles/common/_variables.scss
assets/styles/components/ImageSwitcher.scss
assets/styles/components/_HeroSectionLanding.scss
assets/styles/components/_Table.scss
assets/styles/elements/_Typography.scss
assets/styles/shortcodes/Clients.scss
composer.lock

Fixes and improvements for desktop and mobile of new Solutions pages
Close QualityUnit/web-issues#3330

[3330] feat: fixes for mobile

---

assets/scripts/custom/responsiveTable.js

Hotfix for icons missing in tables

fix: condition for icons in table

---

assets/styles/components/_CodeBlock.scss
assets/styles/elements/_Typography.scss

Fix look of prompt code when <code> tag used
Close QualityUnit/web-issues#3336

[3336] fix: prompt code

---

assets/scripts/custom/responsiveTable.js
assets/styles/common/_variables.scss
assets/styles/elements/Header/_HeaderNavigationMain.scss
assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
base.php
lib/functions.php
lib/functions/custom-main-menu.php

icon animation global
Close QualityUnit/web-issues#3242

[3242] fix: icon animation

---

assets/styles/components/_BannerLandingBlock.scss
assets/styles/components/_BenefitsBlock.scss
assets/styles/components/_HeroSectionLanding.scss
assets/styles/components/_TrainingCourseBlock.scss
assets/styles/shortcodes/Clients.scss

Changes styles for AI-Training page
- Go to AI Training page abd check visual view
**Checklist**
Close QualityUnit/web-issues#3309

[3309] - fix: changes styles for AI-Training page

---

assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
assets/styles/elements/_Button.scss

fix: few minor css tweaks

---

assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
lib/functions/custom-main-menu.php

Changed tag h3 to div and added style for SEO optimisation
- Go to any page whith top menu and check tags in items of sub menu 
**Checklist**
Close QualityUnit/web-issues#3344

[3344] - fix: changed tag h3 to div and added style for it

---

assets/styles/components/compactHeader.scss

fix bugged desgin of chatbot chat in the header
**Checklist**
Close QualityUnit/web-issues#3253

[3253]: Fix /ai-tools/simple-chatbot-google-search-template/

---

lib/components/post-sidebar.php

Changed link to demo on sidebar
- Go to articles of blog and check button link on sidebar
**Checklist**
Close QualityUnit/web-issues#3366

[3366] - fix: changed link to demo on sidebar

---

lib/shortcodes/elementor-blog-posts.php
templates/content-archive.php

Changed list articles (blog page) from blog categories (articles with multiple categories)
and list of three latest articles of blog category (with sub categories) on front page 
- Go to /blog/ and check articles with multiple categories ('Blog' + other categories)
- Go to frontpage and check section "Discover latest AI Innovations" (need three latest articles from
blog categories and subcategories)
**Checklist**
Close QualityUnit/web-issues#3369

[3369] - no blogs between feb 8th and feb 23rd

---

assets/styles/components/_CookieBar.scss
templates/footer.php

Changed styles cookies
- Go to e. g. home page in incognito and check new visual view
**Checklist**
Close QualityUnit/web-issues#3364

[3364] - fix: changed styles cookies

---

assets/styles/common/_typography.scss
assets/styles/common/_variables.scss
assets/styles/components/ElementorBlogPosts.scss
assets/styles/components/_BlockDark.scss
assets/styles/components/_FAQ.scss
assets/styles/components/_FlowModular.scss
assets/styles/components/_HeroBanner.scss
assets/styles/components/_HeroSectionLanding.scss
assets/styles/components/_SolutionsBlock.scss
assets/styles/elements/_Typography.scss

Updated styles and some structure of sections in home and solution pages
- Go to home and solutions pages and check visual changes
**Checklist**
Close QualityUnit/web-issues#[ISSUE_NUMBER]

[3361] - solution home page bugs

---

assets/styles/common/_variables.scss
assets/styles/elements/_Checklist.scss
assets/styles/layouts/Post.scss
assets/styles/layouts/_BlogPost.scss
lib/widgets/chatbot-output/src/scss/style.scss
lib/widgets/tip/src/scss/style.scss
package.json

Updated some styles and add command for package.json (build:all)
- Go to articles of blog and check each element from this issue
**Checklist**
Close QualityUnit/web-issues#3345

[3345] - quote element for flowhunt blog article fix

---

base-scripts.php

I replaced google tag ID because was LA gtag ID is there
**Checklist**

fix: replaced correct gtag id

---

assets/styles/elements/_LabelTag.scss
assets/styles/pages/Pricing.scss

Added trial information tabs to styles, will add to pricing once deployed
Close QualityUnit/web-issues#3379

[3379] feat: adding trial info to pricing page

---

assets/styles/layouts/Post.scss
assets/styles/layouts/_BlogPost.scss

Small change for images and lists
- Go to articles of blog pages (like next /blog/openai-o3-mini-ai-agent-a-compact-yet-powerful-ai-model/)
and check number list and border behind image
**Checklist**
Close QualityUnit/web-issues#3345

[3345] - fix: small change for images and lists

---

assets/styles/Elementor.scss
assets/styles/common/_variables.scss
assets/styles/components/_BannerLandingBlock.scss
assets/styles/components/_BlockIcons.scss
assets/styles/components/_BlockWithLabels.scss
assets/styles/components/_HeroBanner.scss
assets/styles/components/_HeroSectionLanding.scss
assets/styles/components/_Labels.scss

Created services page (updated styles)
- Go to draft page https://webadmin.flowhunt.io/?page_id=6702&preview=true
and check visual view and functionality page
**Checklist**
Close QualityUnit/web-issues#3367

[3367] - feat: created Services page

---

assets/scripts/app/app.js
assets/styles/elements/Header/_HeaderNavigationMain.scss
assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
lib/functions/custom-main-menu.php

Changed some styles on top menu. Changed logic adding selected (active) page
in top menu (used JS script instead of PHP)
- Go to any page with top menu and check visual view and
functionality top menu
**Checklist**
Close QualityUnit/web-issues#3363

[3363] - menu small fixes

---

assets/styles/components/_BlockLink.scss
assets/styles/components/_HeroBanner.scss

Fixed media queries and small styles on AI Agents page
- Go to /ai-agents/ and check visual view and functionality page
**Checklist**
Close QualityUnit/web-issues#3350

[3350] - fix: fixed media queries and small styles on AI Agents page

---

assets/styles/common/_variables.scss
assets/styles/components/_CodeBlock.scss
lib/widgets/chatbot-output/src/scss/style.scss

Updated styles for chatbot output and prompt blocks
- Go to blog articles where we have chatbot output and prompt blocks and
check new styles for it
**Checklist**
Close QualityUnit/web-issues#3345

[3345] - fix: updated styles for chatbot output and prompt blocks

---

assets/styles/elements/Header/_HeaderNavigationMain.scss
assets/styles/elements/Header/_HeaderNavigationSubMenu.scss

Fixed styles on top menu (aligned and hover effects)
- Go to any page with top menu and check hover effect on
submenu right "topPost" and aligned logo and items of menu
**Checklist**
Close QualityUnit/web-issues#3363

[3363] - fix: fixed styles on top menu (aligned and hover effects)

---

assets/styles/components/_BlockIcons.scss
assets/styles/components/_Labels.scss

Fixed styled on "Block icons" section and label icon
- Go to /ai-services/ and check visual view of page
**Checklist**
Close QualityUnit/web-issues#3367

[3367] - fix: fixed styled on "Block icons" section and label icon

---

assets/scripts/custom/responsiveTable.js
assets/styles/components/_Table.scss

Changed regex for find "Y" and "N" in tables (changed to icons)
- Go to page where we have table with close/check icons and check
visual view
**Checklist**
Close QualityUnit/web-issues#3371

[3371] - fix: changed regex for find "Y" and "N" in tables (changed to icons)
